export const PAGE_TYPES = {
  TASKS: 'TASKS',
  MY_DAY: 'MY DAY',
  MISSED_TASKS: 'MISSED TASKS',
  FAVORITES: 'FAVORITES',
  COMPLETED: 'COMPLETED',
  PENDING: 'PENDING'
};

export const IS_FAVORITE = {
  TRUE: 'TRUE',
  FALSE: 'FALSE'
};

export const ACTION_TYPE = {
  NEW: 'NEW',
  UPDATE: 'UPDATE'
};
